### ISSUE TITLE
AggregationEnum not found in 9.2 API

### ISSUE THREAD

**Issue by mike-welch** [EnergyExemplarNorthAmerica/Python-PLEXOS-API#11]
When using the 9.2 API to query a solution file we are encountering an error where `AggregationEnum` does not exist. We also observed this with the 9.1 API. Was there a change to where the enumeration is being defined? Our code is working fine with the 9.0 API.

PLEXOS 9.1 introduced a change in the desktop app for how aggregations are performed, is this related?

PLEXOS 9.0 |  PLEXOS 9.1
--- | ---
![image](https://user-images.githubusercontent.com/19764934/234604910-3158fc8b-a557-4520-a0e9-49ad2bf941ac.png) | ![image](https://user-images.githubusercontent.com/19764934/234604855-235b1b61-d271-45c1-a331-f631e7b844fe.png)

**Comment by Dsce2023** [comment]
I got the same issue. I reported this problem to Energy Exemplar support team two weeks ago, they have not responded to me.

**Comment by mike-welch** [comment]
I reviewed what @JulianAtEnEx changed in #14 and I believe it closes this issue. 

Generally, starting with PLEXOS 9.1 the `AggregationEnum` was replaced with `AggregationTypeEnum` (and it's companion `OperationTypeEnum`) which is available in `PLEXOSCommon.dll`. 

With PLEXOS 9.2, these enumerations have the following values:

```
OperationTypeEnum
	SUM = 0
	AVERAGE = 1
	MIN = 2
	MAX = 3

AggregationTypeEnum
	None = 0
	ObjectAggregation = 1
	CategoryAggregation = 2
	PeriodAggregation = 3
	ListAggregation = 4
```


---

```python
import clr
clr.AddReference('PLEXOSCommon')

from PLEXOSCommon.Enums import AggregationTypeEnum, OperationTypeEnum
```

**Comment by adas18** [comment]
I'm using: 

                          '', \
                          '',\
                          AggregationTypeEnum, \
                          '2', \
                          '', \
                          '', \
                          OperationTypeEnum, \
                          '1')

to generate the average value of a category and getting an error. What is the mistake here?

**Comment by mike-welch** [comment]
> I'm using:
> 
> ```
>                       '', \
>                       '',\
>                       AggregationTypeEnum, \
>                       '2', \
>                       '', \
>                       '', \
>                       OperationTypeEnum, \
>                       '1')
> ```
> 
> to generate the average value of a category and getting an error. What is the mistake here?

It looks like you're adding new terms to the function, which the API won't like. Give this a try and see if it works:

```
                      '', \
                      '',\
                      '2', \  # AggregationTypeEnum
                      '', \
                      '', \
                      '1')  # OperationTypeEnum
```

If using the values doesn't work you'll need to use the full enumeration like is used here:
https://github.com/EnergyExemplarNorthAmerica/Python-PLEXOS-API/blob/f90ea63b1abe431829c52129ea75da1f33c4a909/Solution%20Files/aggregate_by_category92.py#L61-L76

**Comment by adas18** [comment]
Thank you Mike. Tried it both the ways, still getting the same error (mostly just an error in syntax on my part). But thankfully, the category I'm trying to generate the results for defaults to the mean value when looking over a month.

**Comment by jpaduart** [comment]
Hi,

Trying to migrate to 9.2 here as well. There's a type in Mike's suggestion:
it should be PLEXOS*Common*.dll instead of PLEXOSConnect.dll (which doesn't
exist).
After that you can import as follows: from PLEXOSCommon.Enums import
AggregationTypeEnum

Best regards,

Johan.


Op ma 12 jun 2023 om 23:19 schreef adas18 ***@***.***>:

**Comment by adas18** [comment]
Thanks Johan. As an added note for anyone with a similar issue, I found it easier to just query the results on an interval basis and then do the data manipulation/aggregation on the generated dataframe. Allows greater maneuverability, and also was the suggested approach by Energy Exemplar. 

Best, 
Arkadeep

**Comment by mike-welch** [comment]
@jpaduart thank you for catching that typo, I had it correct in my notes but as it goes... I edited my post above to correct for it.
