### ISSUE TITLE
ComplementEnum Query

### ISSUE THREAD

**Issue by Jonai-DeMaggio** [EnergyExemplarNorthAmerica/Python-PLEXOS-API#17]
Is there a way to query via the ComplementEnum instead of the CollectionEnum?

**Comment by mike-welch** [comment]
@Jonai-DeMaggio, I have an old comment in some code about this very issue...

```python
with plx.Solution(p) as sol:
    ## Get Regional Generation Data
    # NOTE: "NodeGenerators" is a complement, not a collection!
        for region in sol.GetChildMembers('SystemRegions'):
            ## Get Generator Data
            df = sol.Query(
                phase='ST',
                period='Interval',
                series='Statistics',
                collection='SystemGenerators',
                child=sol.GetChildMembers('RegionGenerators', region),
                props='NetGeneration',
                aggregation='Category',
            )
            # do stuff                    
```

I think I wanted to use `NodeGenerators` as the Collection for my query but got an error, so instead I approached the problem using `SystemGenerators` and passing a specific list of children to the query. I'm not sure if that will work on nodes, but I would expect `sol.GetChildMembers('NodeGenerators', my_node)` to work.

Let me know if that resolves your issue!

**Comment by Jonai-DeMaggio** [comment]
@mike-welch 

Thank you so much for you response!

This did not quite work for me, but it definitely helped me make a work around.

I think it didn't work as is because of how the memberships in our system are setup. There are no direct memberships between our generators and regions, only between generators and nodes - and then nodes and regions. With that said, I was able to find a work around in which I reference the nodes in the generators to then reference the regions for those nodes:

```
for gen in db.GetObjects(ClassEnum.Generator):
    for comp in db.GetChildMembers(CollectionEnum.GeneratorCompanies,str(gen)):  
        for node in db.GetChildMembers(CollectionEnum.GeneratorNodes,str(gen)):
            for reg in db.GetChildMembers(CollectionEnum.NodeRegion,str(node)): 
                if gen.find('*')>=0:
                    out_file.write(gen + ',' + comp + ',' + reg + '\n')

```

Thank you for your help!
