### ISSUE TITLE
How to access a Cluster with Plexos-API ?

### ISSUE THREAD

**Issue by polysillycon** [EnergyExemplarNorthAmerica/Python-PLEXOS-API#3]
Plexos 8 allows for organizing the Clients into Clusters of clients, but the PLEOXS 7 API doesn't seem to support this.  

Can you please provide an example how to create a Run and send the work to the cluster name ?

**Comment by stevenbroad** [comment]
@polysillycon Sorry about the delay, I have only just seen this question. I will look into this item.

**Comment by stevenbroad** [comment]
I apologize for the extremely long delay in responding. I learned recently that if you terminate the name of the cluster with the symbol known as "pipe" or "vertical bar" specifically the | character, that it will look for that folder of connect clients. For example if you have Client1, Client2, Client3 in PLEXOS Connect and a folder called MyClients containing Client1 and Client3, when selecting to launch a simulation you can specify that the client name is MyClients| and it will route the simulation to either Client1 or Client3.
