### ISSUE TITLE
Question on filtering data to query

### ISSUE THREAD

**Issue by mike-welch** [EnergyExemplarNorthAmerica/Python-PLEXOS-API#5]
I've been working with the API to pull data from a solution file running several stochastic samples due to data volume (the solution file is ~3GB compressed). I used example from the repo as my guide, with snippets like this being especially useful:
https://github.com/EnergyExemplarNorthAmerica/Python-PLEXOS-API/blob/3032b3f0d73231dd0eef6f9a946865f5f1ef283e/Solution%20Files/query_to_pandas.py#L50-L56

I've been able to develop a nice wrapper around `Query` to perform some useful things, like concatenating data for multiple properties (when I don't want all of them). Recently, I've been setting `child` to the name of each generator to pull hourly data and concatenate it into a larger dataset. I'm wondering if there is an off-the-shelf method to pull data by generator category instead?

For example, if I wanted to get the data for all units in the "Coal/Steam" category, in the Solution Viewer I would select the category and run the query:
![image](https://user-images.githubusercontent.com/19764934/124926350-6de4d300-dfcb-11eb-9557-c759c46bf9b3.png)

With code, the only way I can think of to do this is to continue to loop over this subset of generators.

---

Related to the above, is there a good way to pull metadata, such as these memberships from the solution file? Currently I have a CSV I put together from pulling data in the Solution Viewer, but it would be great to programmatically perform this step. There might be an opportunity to pull this information from the database but I haven't explored that option and would rather not introduce a second file.

**Comment by mike-welch** [comment]
I was poking around the other repo and saw the following signature: 
```
    Boolean QueryToCSV(
            String strCSVFile,
            Boolean bAppendToFile,
            SimulationPhaseEnum SimulationPhaseId,
            CollectionEnum CollectionId,
            String ParentName,
            String ChildName,
            PeriodEnum PeriodTypeId,
            SeriesTypeEnum SeriesTypeId,
            String PropertyList[ = None],
            Object DateFrom[ = None],
            Object DateTo[ = None],
            String TimesliceList[ = None],
            String SampleList[ = None],
            String ModelName[ = None],
            AggregationEnum AggregationType[ = None],
            String Category[ = None],
            String Separator[ = ,]
            )
```
[[source]](https://github.com/EnergyExemplarNorthAmerica/PLEXOS-Analysis-Scripts/blob/86497aafe2ef1bc8a00310919d93724ebf89964b/Congestion%20Analyzer/Line%20Congestion%20Analysis.py#L79-L98)

I'm still reviewing this functionality and how `Query` can be updated to include these arguments. I also have a TODO to check the performance difference between `Query` and `QueryToCsv`.

---

Some other notes for later:
- If using `SampleList`...
    Value | Statistic
    --- | ---
    any positive value | the associated sample ID
    `0` | Mean
    `-1` | Standard Deviation
    `-2` | Min
    `-3` | Max
    
    Multiple samples can be queried with a comma-separated string, consider using `','.join(samples)` where `samples` is a list of IDs
- `DateFrom` and `DateTo` must be datetime objects (`System.DateTime`) but `None` can be used to use the simulation bounds
- It appears that `Parent` and `Child` can be `None` or an empty string ''

**Comment by sriharikakuppa** [comment]
Hello Mike, 

Yes the snippet you found is the one to query the generators or any other class by their category (you can set it to none if not interested), and this can be used to query by samples or only for the desired number of samples. In my experience, I found QuerytoCSV to be faster.

**Comment by mike-welch** [comment]
Thank you Harika. I had some time to loop back to this and can confirm that `QueryToCSV` runs faster - I'm observing about 3x. 

I also had the opportunity to catch up on the xPert Training Series and found the session from June 16 to be very helpful: https://marketing.energyexemplar.com/xpert-training
