### ISSUE TITLE
PythonNET Version 3.0.0 Breaking Changes

### ISSUE THREAD

**Issue by mike-welch** [EnergyExemplarNorthAmerica/Python-PLEXOS-API#6]
I tested a prerelease of [`pythonnet`](https://github.com/pythonnet/pythonnet) (specifically version [`3.0.0a2`](https://pypi.org/project/pythonnet/3.0.0a2/)) and had to make a few changes to utilize it:

- enumerations no longer return the integer value, I was able to reproduce previous behavior with `str(ENUM.value__)`
  - this codeblock may not work:
    https://github.com/EnergyExemplarNorthAmerica/Python-PLEXOS-API/blob/24b69a6709b9b28f86e58aa7d45d2d2152d5fa13/Solution%20Files/query_to_pandas.py#L66-L75
- I was not able to convert ADODB recordsets to pandas data frames with the following code:
  https://github.com/EnergyExemplarNorthAmerica/Python-PLEXOS-API/blob/94fa63e2d0232a70f42735a0246b2576fc07eca3/Solution%20Files/query_to_pandas.py#L63-L65 
  - ultimately this was okay since using `Solution.QueryToCSV()` works better (for me anyways) then using `Solution.Query()` followed by the above codeblock

**Comment by stevenbroad** [comment]
Hi Mike, thanks for that feedback. I think generally that QueryToCSV or QueryToList is preferred for performance reasons. I will plan to refactor the Query statements to QueryToList so that we can avoid the need for csv files.
