### ISSUE TITLE
Extracting hourly generation 

### ISSUE THREAD

**Issue by Peslier53** [EnergyExemplarNorthAmerica/Python-PLEXOS-API#7]
Hi,

I am trying to extract hourly generation from plants with the following query that works perfectly at yearly level, but gives me "'NoneType' object has no attribute 'EOF'" when I run it at hourly resolution. Any idea what is going wrong and how i could query hourly generation data ?

Many thanks,

```
results = sol.Query(
    SimulationPhaseEnum.STSchedule, CollectionEnum.SystemGenerators, 
    '', '', PeriodEnum.Interval, SeriesTypeEnum.Values, 
    make_property_list(
        SystemOutGeneratorsEnum.Generation
        )
    )
```

**Comment by stevenbroad** [comment]
That error means that the Query method returned None. Usually this happens because the thing you are requesting is not in the output dataset. Please try querying the dataset to make sure that Interval level generation is actually available in the output in STSchedule.

**Comment by stevenbroad** [comment]
Old issue. Closing
